"""add additional field to tour points

Revision ID: 15006cff2bc6
Revises: 2510f2a33cad
Create Date: 2025-03-11 17:55:04.245067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15006cff2bc6'
down_revision: Union[str, None] = '2510f2a33cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rout_point', sa.Column('point_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rout_point', 'point_name')
    # ### end Alembic commands ###
