"""added currecny table

Revision ID: ba4187d15642
Revises: 15006cff2bc6
Create Date: 2025-03-29 14:03:56.684351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4187d15642'
down_revision: Union[str, None] = '15006cff2bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usd_usd', sa.NUMERIC(precision=10, scale=5), nullable=False),
    sa.Column('usd_eur', sa.NUMERIC(precision=10, scale=5), nullable=False),
    sa.Column('usd_rub', sa.NUMERIC(precision=10, scale=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
