"""added promos

Revision ID: ef0e98226287
Revises: b295c43fc36f
Create Date: 2025-04-13 19:38:45.798527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0e98226287'
down_revision: Union[str, None] = 'b295c43fc36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('promo_type', sa.String(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('promo_start', sa.DateTime(), nullable=False),
    sa.Column('promo_end', sa.DateTime(), nullable=False),
    sa.Column('use_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_code_rout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('rout_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.ForeignKeyConstraint(['rout_id'], ['rout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promo_code_rout')
    op.drop_table('promo_code')
    # ### end Alembic commands ###
